### ISSUE TITLE
Methodology: split actionability into mitigation and detection

### ISSUE THREAD

**Issue by marcnil815** [center-for-threat-informed-defense/top-attack-technique#5]
First off: great work, the methodology is pure gold. Hopefully the community and the big ones will provide more data as this matures.

### Problem
As a defender the actionability of a technique is of importance, however, mitigation does not always correlate well with detection.

The technique with the highest actionability (based on the Calculator.xlsx) is `T1190 - Exploit Public-Facing Application`. Detection on this technique is notoriously difficult, so to get the actionability for a SOC I would want to set the weight of mitigation to zero, which I cannot do with the methodology that is used.

When choosing where to focus for detection and response, a high actionability score due to a high mitigation factor can result in defenders focusing on the wrong techniques in terms of ROI.

### Suggestion
Decouple the actionability into two distinct parameters of mitigation and detection to avoid implied correlation. Often this is done by separate teams with separate focus, albeit with the same goal.

The TOP 10 would then be calculated as:
prevalence  + choke point + detection actionability + mitigation actionability

Since the mitigation score is calculated on abstract controls (CIS, NIST), it stands to reason that they only "suggest" mitigation, without any proof as to their real world efficacy (mitigation fails all the time).

**Comment by mticmtic** [comment]
Hi @marcnil815 . Thanks for reaching out with your feedback. It's nice to see people using our work, and even better when they have suggestions on how to improve it. 

This is an interesting point you bring up. When originally crafting actionability, the idea was if a defender "could take action against the technique." This can be accomplished either with mitigations or detections. I do see the value, however, in splitting them up because most likely different teams will be handling those tasks, as you mentioned. 

I will add this to our backlog and add this to our next release. Thanks again for the suggestion!
